In [1]:
import numpy as np 

In [2]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [3]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones(3)

array([1., 1., 1.])

In [8]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.random.rand(4) # 4 nums between 0-1 

array([0.73562573, 0.53416585, 0.86800707, 0.79384986])

In [12]:
# np.random.randn(2, 4)
np.random.randn(4)

array([-0.12835242,  0.58225684,  0.33614031, -0.46651254])

In [13]:
# np.random.randint(0, 10)
np.random.randint(0, 10, 5)

array([8, 2, 4, 8, 1])

In [14]:
np.random.randint(0, 10, 50).reshape(5, 10)

array([[7, 2, 6, 3, 1, 1, 9, 4, 3, 0],
       [6, 2, 4, 0, 0, 4, 4, 3, 2, 6],
       [9, 2, 7, 6, 3, 9, 2, 1, 0, 8],
       [6, 3, 6, 2, 3, 1, 9, 6, 7, 3],
       [2, 5, 1, 7, 4, 0, 1, 6, 3, 0]])

In [15]:
print(arr)
print(arr.max())
print(arr.min())
print(arr.argmax()) # index
print(arr.argmin())
print(arr.shape)
print(arr.dtype)
print(arr[arr>=2])

[1 2 3]
3
1
2
0
(3,)
int64
[2 3]


In [16]:
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.cos(arr))
print(np.log(arr))

[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[0.         0.69314718 1.09861229]


In [17]:
print(np.sum(arr))
print(np.std(arr))

6
0.816496580927726
